### ISSUE TITLE
Rating performance shouldn't be Infinity for rank 1

### ISSUE THREAD

**Issue by ryski** [meooow25/carrot#36]
Hey,

I have observed that this extension is showing rating performance as infinity for rank 1. I don't think it should be that, maybe there are some off by one errors in the code?

![image](https://user-images.githubusercontent.com/3888766/108164236-6a34da80-7116-11eb-91a7-10785b813675.png)

**Comment by meooow25** [comment]
Hi, that is working as intended.

Performance is the rating at which your delta would be zero.  
But if you're rank 1, you _always_ get a positive delta regardless of your rating.  
I've chosen to show that as inf performance.
