### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by Aadit-Ambadkar** [meooow25/carrot#45]
https://github.com/meooow25/carrot/blob/3befcc942957ba2d5a4a465e5446bae80149ac08/carrot/src/content/content.js#L7

This Unicode escape character doesn't work on my local. Maybe change it? Also in that entire section adding words to explain what the symbols mean might be helpful.

**Comment by meooow25** [comment]
Please see the pinned issue #37. Does it work for you?

> Also in that entire section adding words to explain what the symbols mean might be helpful.

I'm not sure if that's necessary, it's just arrows.
