### ISSUE TITLE
Unrated Users have Rating 0 for Performance Calculations

### ISSUE THREAD

**Issue by Noobie99** [meooow25/carrot#52]
I do not know about live prediction calculations but at least for performance calculations after the contest is done, unrated users count as having rating 0 instead of the default rating of 1400.

I believe this is because the ratingChange api response returns rating 0 but the default rating is only used if the rating is null.

One possible fix would be to also use default rating if the rating is zero. There may be some false positives who actually have rating zero but they should be negligible, as there currently is no active user who has that rating. I tested this and it seems more accurate than before.

**Comment by meooow25** [comment]
First, sorry for the incredible latency here.

> ...unrated users count as having rating 0 instead of the default rating of 1400.

This is not too surprising. It is a part of the whole fake rating problem (#18 for details).

> One possible fix would be to also use default rating if the rating is zero. There may be some false positives who actually have rating zero but they should be negligible, as there currently is no active user who has that rating. I tested this and it seems more accurate than before.

Note that this change does not help with users with fake ratings other than 0. Neither can I think of some other easy way to detect them. So prediction will remain inaccurate with such cases in the data.

So this is a not a complete fix, but I agree that this sounds like an improvement overall.
