### ISSUE TITLE
not showing rating changes in educational round 

### ISSUE THREAD

**Issue by Aniketsingh54** [meooow25/carrot#57]
i refreshed many times it is not showing the performance and rating changes

**Comment by meooow25** [comment]
Thanks for reporting, but this is a problem with the Codeforces server again (see #55, #56).
![image](https://github.com/meooow25/carrot/assets/13716304/2846071f-9f4e-40b7-b9a6-7218cc3ac1ca)

If the server is not serving the correct responses, there is nothing the extension can do about it.

**Comment by Aniketsingh54** [comment]
oohhk i got it now.. they are restricting robots using cloudflare to reduce traffic
