### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UditUchiha** [meooow25/carrot#58]
Showing error:-
Error: CF API: HTTP error 403: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring div{border-color:#999 transparent transparent}body.dark .font-red{color:#b20f03}body.dark .pow-button{background-color:#4693ff;color:#1d1d1d}body.dark #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.dark #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}body.light{background-color:transparent;color:#313131}body.light a{color:#0051c3}body.light a:hover{color:#ee730a;text-decoration:underline}body.light .lds-ring div{border-color:#595959 transparent transparent}body.light .font-red{color:#fc574a}body.light .pow-button{background-color:#003681;border-color:#003681;color:#fff}body.light #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body.light #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}a{background-color:transparent;color:#0051c3;text-decoration:none;transition:color .15s ease}a:hover{color:#ee730a;text-decoration:underline}.main-content{margin:8rem auto;max-width:60rem;width:100%}.heading-favicon{height:2rem;margin-right:.5rem;width:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{height:1.5rem;width:1.5rem}}.footer,.main-content{padding-left:1.5rem;padding-right:1.5rem}.main-wrapper{align-items:center;display:flex;flex:1;flex-direction:column}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{font-size:2.5rem;font-weight:500;line-height:3.75rem}.h2{font-weight:500}.core-msg,.h2{font-size:1.5rem;line-height:2.25rem}.body-text,.core-msg{font-weight:400}.body-text{font-size:1rem;line-height:1.25rem}@media (width <= 720px){.h1{font-size:1.5rem;line-height:1.75rem}.h2{font-size:1.25rem}.core-msg,.h2{line-height:1.5rem}.core-msg{font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI2ZjNTc0YSIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjZmM1NzRhIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);padding-left:34px}#challenge-error-text,#challenge-success-text{background-repeat:no-repeat;background-size:contain}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);padding-left:42px}.text-center{text-align:center}.pow-button{background-color:#0051c3;border:.063rem solid #0051c3;border-radius:.313rem;color:#fff;font-size:.875rem;line-height:1.313rem;margin:2rem 0;padding:.375rem 1rem;transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease}.pow-button:hover{background-color:#003681;border-color:#003681;color:#fff;cursor:pointer}.footer{font-size:.75rem;line-height:1.125rem;margin:0 auto;max-width:60rem;width:100%}.footer-inner{border-top:1px solid #d9d9d9;padding-bottom:1rem;padding-top:1rem}.clearfix:after{clear:both;content:"";display:table}.clearfix .column{float:left;padding-right:1.5rem;width:50%}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center}.footer .ray-id code{font-family:monaco,courier,monospace}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{clear:none;content:none;display:initial;text-align:center}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative}.lds-ring,.lds-ring div{height:1.875rem;width:1.875rem}.lds-ring div{animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;border:.3rem solid transparent;border-radius:50%;border-top-color:#313131;box-sizing:border-box;display:block;position:absolute}.lds-ring div:first-child{animation-delay:-.45s}.lds-ring div:nth-child(2){animation-delay:-.3s}.lds-ring div:nth-child(3){animation-delay:-.15s}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(1turn)}}@media screen and (-ms-high-contrast:active),screen and (-ms-high-contrast:none){.main-wrapper,body{display:block}}.rtl .heading-favicon{margin-left:.5rem;margin-right:0}.rtl #challenge-success-text{background-position:100%;padding-left:0;padding-right:42px}.rtl #challenge-error-text{background-position:100%;padding-left:0;padding-right:34px}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "codeforces.com",cType: 'managed',cNounce: '60393',cRay: '89233559ab5c548a',cHash: '426b5bac1266019',cUPMDTk: "\/api\/contest.standings?contestId=1985&__cf_chl_tk=8m5U7O5pWRcap_uA1kzw1w51GCH1a66wk5.WdClxweg-1718125761-0.0.1.1-4052",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '390000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/api\/contest.standings?contestId=1985&__cf_chl_f_tk=8m5U7O5pWRcap_uA1kzw1w51GCH1a66wk5.WdClxweg-1718125761-0.0.1.1-4052",md: "mpJGhdMiUfPQgInnjUHpCG1X9nO.yVHfrpKYq9iK9Xw-1718125761-1.1.1.1-6mzA7GTbFON_a6XU9hMr1F37fEeBUXJGAmYVWDT7LiNZmcJ.TBN7s5ZcZUc4jW8eYfnvNSZXJn8JIcMWmGe_rB1ACWIfqF.upI1rndt5HhMgYpOormnqTZg7hJXy.YCGF8vJMuSfipk6.Lhe_iVjpO8285et.Piakw4gKx5OmZmHHZiUEnNduaJsMeAKTHIGp.s1EqmGgXayQOnMqGSE8Mii7F5jURsseVzUzRIGjGyrs6tcgnJUwkxxQ1z8RDhnxjvOX8lU5VZC_alZlOUfExIPkvTM4lZLv8yrOhX9n7WV2de_L6qMXPBwVyvKAXdFWhY.h7Z4EKayZoT.MfiMyAxtWYHKdG.JLpdoOAxapPNurjpakuneHYzkpeZCYyeN8GhkzayupojRKXebmug.4R0dWIsA25dUMy2TtdFVGna7VWdZhL_eYpNMzLTi1Ms3up2kJPfJaehoyqLbGEJSj7aoGUWIamgtOzUlLS0kT_6A2dvcK2C9N0CMSW4ASBB7YUAN_LWdsXWiQXOA0qryhIEJLoUgetjnRHXzzNLRT5pk32ErCpDPMe2W7uSVMsPRzdLZudi1BEQP5rWLgw53OfdCY5wVTW5CdoJG_4iujhgHDlp80ekCYkJYUVnUdCfcnyAkKQhQ2ld7fYWBdjn3oq1HpWv.VTn8o_OcwRwNu5n6tKypUQNoNYMZ0DO2c7V3Oc7bq0C5EsLv1M13e5LdskQhaFSFtjv.Xtf2kN.o4aq2U0xtw5ybVlxYwQxvPMKnUEp0K6t2uBzLHAKrtDqC6pcH4yQjkh4a5GWb2gxAz8bW.jdff8uLa.Q4y9.81tbMRTY8Nr.qVGGcZvgkuvkfil0Sv6.LUmuNNhaoFdhyFV.OZ8PZcUr.J_ZOze.htItD1jfJf40FDP1Y6MOL.rM7d8_WL2LSs0gcfMRI97Tp4uEjeuX.tw4rxIP5Mzj00dbI3Eo8p6a6BN_MlW43aM1GmZomqr8sl6maVu2Yzv_WXVkLIIq4Ap2KG7g2cyEvOaYB3bsYedyB7xiojTJmBmYBhhygvXdutpa2fUMmuH5yTToG._T_HGSmBjtVKO5V3VYEKkW3VQbjvn1hKS4oo3kut65r1KpyyWAPWr8IEqwyqtDDD_jH_5tJXsurtBhn4uHkjpJ3iU68.y8d2YM31CR0wREy.poVdglICjb3oj_uHJAiQ_ZPk58CTYigzIhkkYX7bsUihC5ZN6A3Ky6yV2h7obrScLWQ90Epw338yg5nEM1UTG2SAsi2Efw.cDKhCt7PygxU5AjY8D3wcJ4jugIG85EEPlnTb9d6AArolF.W3D4njYNnQPBMYNiSLkBoXZ9ksC846WPXhFnnvOE4iQEFv08Z_NZlOdAEw.G8bapdkD1JXs0Unxjr0N5olKgaOB.7C.PBi9tt981aZUa2fwMTbmGDqccc.qllxoAS.i9Leroi2rQ0f1ZXvhe2cJtdBx5C8f3jHQjgBRDt4bSGMXCUHxb1rSCq_gXKtcR6Hwc.SHM",mdrd: "umCewACCIyWSOMdp05rWWBvna8r.EgDmVz4cLEP1qrQ-1718125761-1.1.1.1-plhtsbRVXqNF7B8eW19D8uo56TcS0yp4nvPKxhWzAsEFAHC53RSHCI6kZfliYLgYmRfbRq7PIbj7T9azw9LMGdzDW9pd60.WRnx1rovGkpmSLEZcVuv8eq3vptl0XFvjCQ7eVTBzwN0zJ0vwO8A4LJJCBaAaEJo9oyBYFkjEWcUez7lK.nXSNQYVr7SBKajvRZAcS4X4ENprPL3Woh3.Hw38.Bd_guUroqAhWgAs7euiPafKAJ0V2X2_wrFbufaxYIj22.nFP2UqJ2obeoIjM7MT8_GFnWGnrGqfWdPgAQfqAAjjFa6b9HR_xQ3IFjGJ_lKjYwmhoKqWfQZS2ExmYmitaPMebqiBOUfB0IAtlR_V0Y95Kb4eYhK00SdrSnG3RSj6Qc1n5H_2zFQiArO3HI9sGaU8PBqeaplS17HH9sQb0OsE6.z7sXxlY.hLON4QZFyux26tMd4TOjlGulFCI8amwG6v2kYP1nLVZv_S_Pxy0QHPg.Of8lLaxj3St7amAeJAMQ6x5eg.vCuZE4naxN3bVncXHKrfRaf0zv3tStW.CaJqitW46_V5mQDAwrz.98ECx6Mt39IlnXOPlEvW0nVZoDSIWRfYp4NyW.NVszt4nRi6mkjI4889H41cx0Y7vsegsLyW4WmaQig9cPGk9bUWEyinnkMef5IPZTw3uzCqK6pwArwRGuRwhOmFSDJ_DKlwVwco3kSRVHYUwknAecg6qQINLiuwqswLJp8vp.Tu6zfVfO9Duo5ECEc0VqevFLxzvleZbBIecTzbbPSWzLylCPmBjlBjQJ1GtgyHEFH3pgFfglD35wxC4X206iIo_22YZF8vZiwrCqYUx___f6AjhVVbFbdWDRyS2S.5cQR_nFUXXHJ2BwNy4vLd5e0uNBt5W7W_aqlLHlMijMabLC7HRbcfyxQY57_bJvuTUinAG9zopLv3ZNoCm8tDM0ZX.BZ2rbCsSFLLoQ30WNsnEOH4Y0.9lv3S3Hx79WcGon6VDvDh4MDqy7wO1UaWc_XWYuLe5.Nhc9c6OPeMd1x_Lz3UFjyql25.MQHnQmuOxGaZnRLm2P9JTd1uCeIIDvN2wBUfnt6FclwHvFd.HUo83ysAqtQk0P.5AD6SCmj.k6B6XAQ_.3L1SklDv8nFApBdeoOLDJp9qmilLdsSBMntTp2WTJ.4swmByAIwk00BpCL3ZmWycqDLZMOk7k28iNv54I1ycyEl90zAdbtST6yawp_An_oLDtpfuf32CCEirInEXWXcLyELXarB9v0B7SFTOVlyiHqe2Ygw9AoFgoFRkvRGkR1LX2fWuxFeE2Fjw9EFrLr2qV63whaQGKlFOMInZsrWlS_1nLCdD6WsTXLiaRHfV4kU9JQ5meXD_U0a8wXqkENJnY_trKOwzg_3vyU_K8WrHBcRCTb9jfR1mflW1uih4iOZ16fOJcWimb9STD32RAfWE9Rzp0AIU5I.Ssg5VNjndfu682BYDHcvcyq66vF6FqiESgiwmG0twzbCHB.tmjB7TW7FCaZX246H9Fip_FeseHU4hdc7sAcUGWE1eO6Al5VX4jTbDyq3nFwt8eXiO8iLuOntTMDy6lbUmETvF2y1s3RLtTCIX4h0H.3xcE9ddPnE9V9TgjFfMbHrxDkXCdLCB22ziShzFF.wTvvSUtW59BMiYV_iVXhcw0adbTab8t.8DrCak76EXG28NErIgmaYpExnNLq63St_0D3QDnDXIy7mFnh8NRfXCDZDVaXWNXkPI6svagOGWw0Q9OSX.eqL6FJrKHszc_a8WTIYZlqFS6M0IwfWH_9ZEs2muv6TohlCqAoPoWjZPgetG3GLEMGtie9ZsVn060bMS5FvVv1RaxRmNwA3U8tC5BJtttbGUPRPg4Tl.CvPEU8_Gf_9l5ROACGN6l7M65LbbuwLH01M7t1ZjlDPJPLXnuAhJqOkK6Jlk_wqP81XX3mRcw43U8yhG6xXhrGzlLDxX_u.C21CjHv2o0WElYcxFMtkMBvWN2VLA0QDs.yQ3y6NsfcIz3tplMv3jF8h6h8F_8cZvPEiHyQqeM5zppCAxln84jiCVk.KjO6T3jKVfAe6AhtUr6TlqnoFhDRctjJDWNsFbCgYskDQ.oVpc6i0y1rcFiFmIT.mzJXTovnYoqUaGswgQAL1Rp7QrwwADYPTLSwYyCgI9XIz0XuvZEmyZLbeoVJYrPPEWCPdP4eFPot2Hgko9w9zdFfcBKgi723gZLm6yTKVDhcA_qaTpiPY7lKTWlLY4udsBSDK0prM_JhpJTbNVbEcImM2fVWoFFSrc98HmlBp28E8SXTpNUuokoClrNNxA5mpbOR9WP6h6Q7TZAGwCT0ObixpIMKerCx7V.BLzQrRP368bGOqQ7GgExtUyLe_AgzQntwkGjOI4NPW6Mc",cRq: {ru: 'aHR0cHM6Ly9jb2RlZm9yY2VzLmNvbS9hcGkvY29udGVzdC5zdGFuZGluZ3M/Y29udGVzdElkPTE5ODU=',ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEyNS4wLjAuMCBTYWZhcmkvNTM3LjM2',rm: 'R0VU',d: 'piZtaASTDqjezjH5H5fztP5AwK1Dkmc9T6DzJRpxmzwatdjarSl7V2e4szu1hOK51nLuBJUFNfYNBwh/tCdanqYWOEk4axBFzsnQsSf6Kd55PgIR2jp83ScgrPooEzo7PP/KHhPm5M7FF0UXXiI+tRop06WrE1sfCRMpV3hhfPCKFXLoxmFdP5BSuyydctViBuWO+Jufjg7X2YvEJRnuChAxyIkjmfxYp/hepNJrlanqPEhH9KTEO0bBd4DZcHfz/MWGk1S4d3PGXLUkh0sVCoIGpensR54otLKIH6xyj9kUQk7niR3/3M4qPGMQN1Oel2Ka7z3E8j3e4x3Qrpxdph/D9UPyiXAbL5W55mIj8I4sNeQ1GsHCIZgNr8Zq7J+XREQ4ji7pcYZ9QJGv5o4znfXGFxXEw0KDYYfYuE/qr2aI4M1W6fWXZ9q3sfjgpcnavw0lajOyS80A/KqDOczgw31v+I1kIi39nY363W7eRVtz+0xtkYB6mnJPl8CjFE/+4mwYK8L8Ll8NX51JINimig==',t: 'MTcxODEyNTc2MS4wMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: 'AyaFmstJwnZVtEJSJ4eYYEXSpdGsrgyC0WIZ1BrUHg0=',i1: 'F/UHFmIaL+XtQdt32Cst9w==',i2: 'pFQ3PaKSN3eh+UqqLVZwwg==',zh: 'gtUvwVv5QSkwHHMJu2hcSNzxeG4KPC9opADL6CDvvtA=',uh: 'thCBy90zqmBonn2dYlU/D+MzVlbuUEXEmRt0jJlmUpg=',hh: 'OIQEPuGe1LQel8eDucs/36uHo6kFKC1xfaprHMgVNMU=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=89233559ab5c548a';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/api\/contest.standings?contestId=1985&__cf_chl_rt_tk=8m5U7O5pWRcap_uA1kzw1w51GCH1a66wk5.WdClxweg-1718125761-0.0.1.1-4052" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
![Screenshot 2024-06-11 224306](https://github.com/meooow25/carrot/assets/97434789/1b01c280-52ff-4303-97aa-d695b07154c6)

**Comment by meooow25** [comment]
Thanks for reporting.

This is a problem with the Codeforces server, which is not responding correctly to API requests. Unfortunately, the extension cannot do anything about it.

This happens once in a while (see #55, #56, #57). The extension will start working again when Codeforces fixes their server.
