### ISSUE TITLE
No longer working during contests. it works only after the contest is finished

### ISSUE THREAD

**Issue by AbdElRahmanOsama182** [meooow25/carrot#59]

**Comment by meooow25** [comment]
Hello, thanks for reporting this, but this is too little to go on. Is there an error message?

**Comment by AbdElRahmanOsama182** [comment]
![image](https://github.com/meooow25/carrot/assets/52374998/eeceb511-f560-4c6a-ae7b-9118197fe0ff)

**Comment by meooow25** [comment]
Oops, forgot to respond here.

If it's an error 403 or 404 like this, it is likely due to the Codeforces server not serving correct responses to API requests. This is known to happen (see #55, #56, #57, #58). Unfortunately, I can't do anything with the extension to improve the situation 🙁. It must use the Codeforces server for its functionality.

**Comment by VCoves** [comment]
I think in some cases we can get correct responses if we impersonate a browser in the request, in python there is curl_cffi https://github.com/lexiforest/curl_cffi I tried during contest to get some web and only with impersonation the request was successfull.

Example code:
import curl_cffi.requests as cf_req
import requests


```
def main():
    base = 'codeforces.com/problemset'
    http_url = f'http://{base}'
    https_url = f'https://{base}'
    for url in [http_url, https_url]:
        for imper in ['chrome', None]:
            response = cf_req.get(url,impersonate=imper)
            print(f"[CURL_CFFI] {response.status_code} url={url} impersonate={imper}  {len(response.text)}")

    for url in [http_url, https_url]:
        response = requests.get(url)
        print(f"[requests] {response.status_code} url={url}  {len(response.text)}")
    
main()
```
Results:
<img width="727" alt="Image" src="https://github.com/user-attachments/assets/3ccccd1c-639d-4e87-9c73-3ec5b5f02c9e" />

**Comment by meooow25** [comment]
We don't need to impersonate a browser. Carrot is a browser extension and the requests are made from the browser.
