### ISSUE TITLE
how to fix "Error: Could not establish connection. Receiving end does not exist."

### ISSUE THREAD

**Issue by mrsunsssss** [meooow25/carrot#70]
![image](https://github.com/user-attachments/assets/2ed1eae2-a187-4b8e-8b63-46b24e0167be)

how to fix it？

**Comment by meooow25** [comment]
Someone told me a while ago that they got this error, but it was a temporary issue which got fixed.

Is it a persistent error for you? Does it reoccur if you restart your browser?

**Comment by mrsunsssss** [comment]
Thank you. I just tried restarting the browser, and the issue has been fixed.
I have encountered it before,and since I didn't try restarting the browser,it would persist for a few days.

**Comment by meooow25** [comment]
Good to hear that 👍 

In general I'm aware of this error, but such situations shouldn't arise at all (for instance, if the the background page sends a message to the content page which has no listener for it). So I don't know what might be going wrong sometimes 🤷

Do leave a comment if it happens again, I'll take a closer look.
